services:

  opensearch:
    image: opensearchproject/opensearch:2.18.0
    container_name: opensearch
    environment:
      discovery.type: single-node
      node.name: opensearch
      plugins.security.disabled: "true"
      logger.level: info
      OPENSEARCH_INITIAL_ADMIN_PASSWORD: SuperSecretPassword_123
    ports:
      - 9200:9200
      - 9600:9600
    networks:
      - opensearch

  dashboards:
    image: opensearchproject/opensearch-dashboards:2.18.0
    container_name: dashboards
    ports:
      - 5601:5601
    expose:
      - 5601
    environment:
      OPENSEARCH_HOSTS: '["http://opensearch:9200"]'
      DISABLE_SECURITY_DASHBOARDS_PLUGIN: "true"
    depends_on:
      - opensearch
    networks:
      - opensearch

networks:
  opensearch:
    driver: bridge
